### ISSUE TITLE
west build running infinitely on standalone sample

### ISSUE THREAD

**Issue by rajeev1986** [edgeimpulse/example-standalone-inferencing-zephyr#24]
**Zephyr Version**
nRF SDK v1.7.0

**Issue**
I started testing edge impulse on my custom device that is built around nRF9160 running Zephyr. Using the data forwarder I was able to connect the device to the edge impulse studio and deploy the model, obtaining a packaged library containing the Edge Impulse C++ SDK. As instructed in the [docs](https://docs.edgeimpulse.com/docs/running-your-impulse-locally-zephyr), I downloaded the .zip file and placed the contents in the 'example-standalone-inferencing-zephyr' folder. The final folder structure looks as such:
```
 example-standalone-inferencing-zephyr
 ├── CMakeLists.txt
 ├── edge-impulse-sdk
 ├── model-parameters
 ├── prj.conf
 ├── README.md
 ├── sample.yaml
 ├── src
 ├── tflite-model
 └── utils
 ```
 
 To confirm if the binary is generated correctly, the zephyr project is first built with `west build -b nrf9160dk_nrf9160ns`. The west build process kicks in, however, seems to be running infinitely without completion. I have waited up to 5 minutes and still, the build does not finish.
 
Attached is the full project. 

[standalone-inferencing.zip](https://github.com/edgeimpulse/example-standalone-inferencing-zephyr/files/7615380/standalone-inferencing.zip)

@ijdoc  and @janjongboom  am I missing something? 
 Would appreciate it if someone could help me fix this.
 
Thanks

**Comment by ijdoc** [comment]
Hello @rajeev1986, I was able to build your project, as is, after extracting the zip file, so I suspect there may be something missing in your toolchain setup. I recommend searching for, or posting, the issue on the [Nordic DevZone](https://devzone.nordicsemi.com/). I am attaching here the log output of the build I ran in case it may provide you with any clues. Alternatively, you can try collecting a log of your build and posting it to this issue, I can take a look and see if I can spot anything out of place. If you do that, details on your toolchain setup would be appreciated (e.g., OS, how you installed your toolchain, anything else you think might be relevant)

[out_log.txt](https://github.com/edgeimpulse/example-standalone-inferencing-zephyr/files/7618802/out_log.txt)
